# Generated by Django 4.1.5 on 2023-06-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=40)),
                ('city', models.CharField(default='', max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('e_mail', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'school_tb',
            },
        ),
    ]
