# Generated by Django 4.1.5 on 2023-06-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
    ]
