# Generated by Django 4.1.5 on 2023-07-06 05:34

from django.db import migrations, models
import school_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='date',
            field=models.DateField(default=school_admin.models.default_date),
        ),
        migrations.AlterField(
            model_name='title',
            name='status',
            field=models.CharField(default='non-active', max_length=50),
        ),
    ]
