# Generated by Django 4.1.5 on 2023-06-20 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('no_votes', models.BigIntegerField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.title')),
            ],
            options={
                'db_table': 'positions_tb',
            },
        ),
    ]
