# Generated by Django 4.1.5 on 2023-06-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0003_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='password',
            field=models.BigIntegerField(default=1),
        ),
    ]
