# Generated by Django 4.1.5 on 2023-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0007_title_date_delete_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='date',
            field=models.DateField(default='2023-06-23'),
        ),
    ]
