# Generated by Django 4.1.5 on 2023-06-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(upload_to='voter/')),
            ],
            options={
                'db_table': 'voter_tb',
            },
        ),
    ]
