# Generated by Django 4.1.5 on 2023-07-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(upload_to='voter/')),
                ('e_mail', models.CharField(default='', max_length=30)),
                ('title', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='school_admin.title')),
            ],
            options={
                'db_table': 'voter_tb',
            },
        ),
    ]
