# Generated by Django 4.1.5 on 2023-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='e_mail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
