# Generated by Django 4.1.5 on 2023-06-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_voter_e_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='college_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
