# Generated by Django 4.1.5 on 2023-06-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_voter_college_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='college_id',
        ),
    ]
