# Generated by Django 4.1.5 on 2023-07-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0008_alter_title_date'),
        ('voter', '0004_remove_voter_college_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='title',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='school_admin.title'),
        ),
    ]
