# Generated by Django 4.1.5 on 2023-07-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_admin', '0001_initial'),
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='candidate/')),
                ('email', models.CharField(max_length=50)),
                ('platform', models.CharField(default='', max_length=100, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.positions')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.title')),
            ],
            options={
                'db_table': 'candidate_tb',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidates')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.positions')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.voter')),
            ],
            options={
                'db_table': 'votes_tb',
            },
        ),
    ]
