# Generated by Django 4.1.5 on 2023-06-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='platform',
            field=models.CharField(default='', max_length=100),
        ),
    ]
