# Generated by Django 4.1.5 on 2023-07-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_votess_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votess',
        ),
    ]
